/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/geocode/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geocode autocomplete (type-ahead).
         * @description Type-ahead variant of `/v1/geocode/search`, billed at a tenth of the cost — fire it on every keystroke from a search bar.
         *
         *     **Quota cost:** 0.1 unit per call.
         */
        get: operations["geocode_autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/geocode/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reverse geocode.
         * @description Turn coordinates into the nearest named place.
         *
         *     **Quota cost:** 1 unit per call.
         */
        get: operations["geocode_reverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/geocode/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forward geocode.
         * @description Turn a place name or address into coordinates. Returns a GeoJSON FeatureCollection ranked by relevance.
         *
         *     **Quota cost:** 1 unit per call.
         */
        get: operations["geocode_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/isochrone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reachable-area polygons.
         * @description Compute reachable-area polygons (isochrones) from one or more origins. Each contour is a time or distance band, returned as a GeoJSON Feature.
         *
         *     **Quota cost:** `5 × L × C` units per call (`L = locations`, `C = contours`). Capped at `L × C ≤ 4`; requests beyond that return 400.
         */
        post: operations["isochrone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Travel-time matrix.
         * @description Calculate the travel time and distance between every source and every target — the cost grows with `M × N`, the number of pairs.
         *
         *     **Quota cost:** `M × N` units per call (`M = sources`, `N = targets`). Capped at `M × N ≤ 2500`; requests beyond that return 400 without charging quota.
         */
        post: operations["matrix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn-by-turn directions.
         * @description Calculate a route between two or more waypoints.
         *
         *     **Quota cost:** 1 unit per call.
         */
        post: operations["route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiles-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sign a tile-server URL.
         * @description Returns a short-lived, IP-bound signed URL for the vector basemap. Feed it to MapLibre's `pmtiles://` protocol handler. Pass a stable `session` id (one per map instance) so background URL refreshes within the session are billed once — the `@rijwind/sdk` tile-session helper manages this for you.
         *
         *     **Quota cost:** 1 unit per tile session; refreshes within the same session are free. Omit `session` to be billed per request instead.
         */
        get: operations["sign_tile_url"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Routing profile. `auto` (car), `bicycle`, or `pedestrian` (foot).
         * @enum {string}
         */
        Costing: "auto" | "bicycle" | "pedestrian";
        DirectionsOptions: {
            /**
             * @description Language for narrative directions.
             * @example en-US
             */
            language?: string | null;
        };
        /** @description Standard error envelope. The `error` field is a stable, machine-readable code; the `message` field is for humans and may be rewritten for clarity between releases. */
        ErrorResponse: {
            /**
             * @description Machine-readable error code, e.g. `quota_exhausted`.
             * @example quota_exhausted
             */
            error: string;
            /**
             * @description Human-readable explanation.
             * @example Monthly request quota exceeded for this key.
             */
            message: string;
        };
        /** @description One contour for an isochrone request — either `time` (minutes) or `distance` (in the request's `units`). `color` is a hex color without the leading hash, used for the rendered polygon's stroke and fill. */
        IsochroneContour: {
            /**
             * @description Hex color without leading hash.
             * @example ff0000
             */
            color?: string | null;
            /** Format: double */
            distance?: number | null;
            /**
             * Format: double
             * @example 15
             */
            time?: number | null;
        };
        IsochroneFeature: {
            /** @description GeoJSON geometry — Polygon or LineString depending on the `polygons` flag. */
            geometry: unknown;
            properties: components["schemas"]["IsochroneFeatureProperties"];
            type: string;
        };
        IsochroneFeatureProperties: {
            color?: string | null;
            /** Format: double */
            contour?: number | null;
            metric?: string | null;
        };
        IsochroneRequest: {
            /**
             * @description One contour per reachable-area band. The product
             *     `len(locations) × len(contours)` must not exceed 4.
             */
            contours: components["schemas"]["IsochroneContour"][];
            costing: components["schemas"]["Costing"];
            locations: components["schemas"]["LngLat"][];
            /** @description Return polygons instead of GeoJSON LineStrings. */
            polygons?: boolean | null;
        };
        /** @description GeoJSON FeatureCollection with one feature per contour. */
        IsochroneResponse: {
            features: components["schemas"]["IsochroneFeature"][];
            type: string;
        };
        /** @description A `(lat, lon)` pair. Latitude is in [-90, 90], longitude in [-180, 180]. */
        LngLat: {
            /**
             * Format: double
             * @example 52.3676
             */
            lat: number;
            /**
             * Format: double
             * @example 4.9041
             */
            lon: number;
        };
        MatrixCell: {
            /**
             * Format: double
             * @description Distance in the requested units. `null` if the pair is unreachable.
             * @example 60.4
             */
            distance?: number | null;
            /** Format: int32 */
            fromIndex: number;
            /**
             * Format: double
             * @description Travel time in seconds. `null` if the pair is unreachable.
             * @example 4810
             */
            time?: number | null;
            /** Format: int32 */
            toIndex: number;
        };
        MatrixRequest: {
            costing: components["schemas"]["Costing"];
            sources: components["schemas"]["LngLat"][];
            targets: components["schemas"]["LngLat"][];
            units?: null | components["schemas"]["Units"];
        };
        /** @description Matrix response. Outer array indexes sources, inner array indexes targets — `M × N` cells in row-major order. */
        MatrixResponse: {
            sourcesToTargets: components["schemas"]["MatrixCell"][][];
            units: string;
        };
        PlaceFeature: {
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["PlaceProperties"];
            /** @description Fixed string `"Feature"`. */
            type: string;
        };
        /** @description Standard GeoJSON FeatureCollection, ranked by relevance. */
        PlaceFeatureCollection: {
            features: components["schemas"]["PlaceFeature"][];
            type: string;
        };
        /** @description Geographic metadata for a place. Optional fields are omitted when the underlying record doesn't carry them — e.g. a country-level result has no `street`. */
        PlaceProperties: {
            /** @example Amsterdam */
            city?: string | null;
            /** @example Netherlands */
            country?: string | null;
            /**
             * @description ISO 3166-1 alpha-2 country code.
             * @example NL
             */
            countrycode?: string | null;
            /**
             * @description Display name of the place.
             * @example Damrak
             */
            name?: string | null;
            /** @example 1012 */
            postcode?: string | null;
            /** @example North Holland */
            state?: string | null;
            /** @example Damrak */
            street?: string | null;
            /**
             * @description What kind of place this is — `street`, `house`, `locality`, `city`,
             *     `district`, `region`, `country`, etc.
             * @example street
             */
            type?: string | null;
        };
        PointGeometry: {
            /**
             * @description `[lon, lat]`.
             * @example [
             *       4.9041,
             *       52.3676
             *     ]
             */
            coordinates: number[];
            /**
             * @description Fixed string `"Point"`.
             * @example Point
             */
            type: string;
        };
        RouteLeg: {
            maneuvers: components["schemas"]["RouteManeuver"][];
            /**
             * @description Encoded polyline at 1e-6 precision (the standard Google polyline
             *     algorithm with 6 decimals instead of 5). Decoders are available for
             *     every major language — in JavaScript, `@mapbox/polyline` with the
             *     precision set to 6 returns `[lat, lon]` pairs.
             */
            shape: string;
            summary: components["schemas"]["RouteSummary"];
        };
        RouteManeuver: {
            /** Format: int32 */
            beginShapeIndex: number;
            /** Format: int32 */
            endShapeIndex: number;
            /** @example Head north on Damrak. */
            instruction: string;
            /** Format: double */
            length: number;
            /** Format: double */
            time: number;
        };
        RouteRequest: {
            costing: components["schemas"]["Costing"];
            directionsOptions?: null | components["schemas"]["DirectionsOptions"];
            /** @description Two or more ordered waypoints. The first is the origin, the last is the destination. */
            locations: components["schemas"]["LngLat"][];
            units?: null | components["schemas"]["Units"];
        };
        /** @description Route response. The interesting fields are `trip.summary` (totals) and `trip.legs[i].shape` (an encoded polyline ready to render). */
        RouteResponse: {
            trip: components["schemas"]["Trip"];
        };
        RouteSummary: {
            /**
             * Format: double
             * @description Total length in the requested units.
             * @example 60.4
             */
            length: number;
            /** Format: double */
            maxLat?: number | null;
            /** Format: double */
            maxLon?: number | null;
            /** Format: double */
            minLat?: number | null;
            /** Format: double */
            minLon?: number | null;
            /**
             * Format: double
             * @description Total travel time in seconds.
             * @example 4810
             */
            time: number;
        };
        /** @description Short-lived signed URL pointing at the basemap on `cdn.rijwind.com`. The signature is bound to the requester's IP and expires after a short TTL — refresh it within a tile session rather than re-signing on a fixed schedule (the `@rijwind/sdk` tile-session helper does this for you). */
        SignedTileUrl: {
            /**
             * Format: int64
             * @description Unix timestamp (seconds) when the signature expires.
             * @example 1715680000
             */
            expiresAt: number;
            /**
             * @description Signed URL ready to feed to MapLibre's `pmtiles://` protocol handler.
             * @example https://cdn.rijwind.com/tiles/planet.pmtiles?token=2Tw9…&expires=1715680000
             */
            url: string;
        };
        Trip: {
            /** @example en-US */
            language: string;
            legs: components["schemas"]["RouteLeg"][];
            /**
             * Format: int32
             * @example 0
             */
            status: number;
            /** @example Found route between points */
            statusMessage: string;
            summary: components["schemas"]["RouteSummary"];
            /** @example kilometers */
            units: string;
        };
        /** @enum {string} */
        Units: "kilometers" | "miles";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    geocode_autocomplete: {
        parameters: {
            query: {
                /**
                 * @description Free-text query, typically a partial input.
                 * @example amst
                 */
                q: string;
                /**
                 * @description Preferred language.
                 * @example en
                 */
                lang?: string;
                /**
                 * @description Maximum number of suggestions.
                 * @example 5
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Autocomplete suggestions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceFeatureCollection"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    geocode_reverse: {
        parameters: {
            query: {
                /**
                 * @description Latitude.
                 * @example 52.3676
                 */
                lat: number;
                /**
                 * @description Longitude.
                 * @example 4.9041
                 */
                lon: number;
                /**
                 * @description Preferred language.
                 * @example en
                 */
                lang?: string;
                /**
                 * @description Search radius in kilometers.
                 * @example 1
                 */
                radius?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reverse-geocode result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceFeatureCollection"];
                };
            };
            /** @description Latitude or longitude out of range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    geocode_search: {
        parameters: {
            query: {
                /**
                 * @description Free-text query.
                 * @example Damrak 1, Amsterdam
                 */
                q: string;
                /**
                 * @description Preferred language (ISO 639-1, or `default`).
                 * @example en
                 */
                lang?: string;
                /**
                 * @description Maximum number of results.
                 * @example 5
                 */
                limit?: number;
                /** @description Bias results toward this latitude. */
                lat?: number;
                /** @description Bias results toward this longitude. */
                lon?: number;
                /** @description Restrict results to a bounding box: `minLon,minLat,maxLon,maxLat`. */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forward-geocode results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceFeatureCollection"];
                };
            };
            /** @description Query parameters failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted (hard-cap plans only). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    isochrone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IsochroneRequest"];
            };
        };
        responses: {
            /** @description Isochrone response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsochroneResponse"];
                };
            };
            /** @description Body malformed, costing unsupported, or `L × C > 4`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    matrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixRequest"];
            };
        };
        responses: {
            /** @description Matrix response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixResponse"];
                };
            };
            /** @description Body malformed, costing unsupported, or `M × N > 2500`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    route: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Route response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Malformed body or unsupported costing profile. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sign_tile_url: {
        parameters: {
            query?: {
                /**
                 * @description Stable, client-minted identifier for the map instance (e.g. a UUID, `[A-Za-z0-9_-]`, ≤128 chars). The first token for a session is billed 1 unit; subsequent tokens for the same session within the session window are free. Omit to be billed per request.
                 * @example 8f14e45f-ceea-467a-9e0b-1c2d3e4f5a6b
                 */
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedTileUrl"];
                };
            };
            /** @description Missing, malformed, or revoked API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Origin not in the project's allow-list. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Monthly quota exhausted (hard-cap plans only). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
